name: News API

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ development ]

jobs:
  build:

    runs-on: ubuntu-latest
    services:
        mysql:
          image: mysql:5.7
          env:
            MYSQL_ALLOW_EMPTY_PASSWORD: yes
            MYSQL_DATABASE: homestead
          ports:
              - 33306:3306
          options: >-
            --health-cmd="mysqladmin ping"
            --health-interval=10s
            --health-timeout=5s
            --health-retries=3

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.ci', '.env');"
    - name: Install dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: composer install --prefer-dist --no-progress --no-suggest
    - name: Migrate & Populate database
      env:
        DB_CONNECTION: mysql
        DB_DATABASE: homestead
        DB_PORT: 33306
        DB_USER: root
        DB_PASSWORD: ''
      run: |
        php artisan migrate
        php artisan db:seed
    - name: Run test suite
      env:
        DB_CONNECTION: mysql
        DB_DATABASE: homestead
        DB_PORT: 33306
        DB_USER: root
        DB_PASSWORD: ''
      run: |
        composer run-script test
